version: "2"
plugins:
  brakeman:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: "rubocop-0-85"
  scss-lint:
    enabled: true
  shellcheck:
    enabled: true
exclude_patterns:
- config/**
- db/**
- app/assets/javascripts/angular-libs/**
- app/assets/javascripts/foundation/**
